name: Sync to GitLab

on:
  push:
    branches:
      - main  # Change this to match your GitHub branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git config --global user.email "mmswflow@gmail.com"
          git config --global user.name "mmswflow-upb"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/mmswflow-upb/greentext-generator.git
          git push --force --mirror gitlab
